version: '2.1'
volumes:
  resin-data:
services:
  browser:
    restart: always
    image: bh.cr/balenalabs/browser-aarch64
    network_mode: host
    privileged: true
    depends_on:
      - paradise
    environment:
      - KIOSK=1
      - LAUNCH_URL=http://127.0.0.1:80/#/controlPanel/help
      - SHOW_CURSOR=1
  paradise:
    build:
      context: .
    privileged: true
    restart: always
    network_mode: host
    environment:
      - PARADISE_DATABASE_PATH=/data/database/paradise-database.sqlite
      - PARADISE_IMAGE_PATH=/data/images
      - PARADISE_LOG_PATH=/data/logs
    volumes:
      - 'resin-data:/data'
    labels:
      io.balena.features.supervisor-api: true
      io.balena.update.strategy: download-then-kill
    ports:
      - 80:80