name: 🎚️ OSC Console Request
description: Suggest a console Paradise Pi OSC should support
title: "[OSC] <title>"
labels: [enhancement]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue or pull request for this?
      description: Please search to see if an issue already exists for this console. Be sure to also check closed issues.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: What is the name of the Console?
      options:
        required: true
  - type: input
    attributes:
      label: Please provide a link to the manufacturer's website
      options:
        required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false