name: Build
on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
jobs:
  build:
    name: Build
    runs-on: os
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install
      - if: os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.0
      - run: npm run package