name: Build for Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm install
      - if: matrix.os == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.1
      - run: npm run publish